#ifndef TUSB_CONFIG_H_
#define TUSB_CONFIG_H_

// TinyUSB uses the RP2040 USB controller for the RP2350 board backend.
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUD_ENABLED 1
#define CFG_TUD_CDC 1
#define CFG_TUD_AUDIO 1
#define CFG_TUD_ENDPOINT0_SIZE 64

#define CFG_TUD_CDC_RX_BUFSIZE 64
#define CFG_TUD_CDC_TX_BUFSIZE 64
#define CFG_TUD_CDC_EP_BUFSIZE 64

#define CFG_TUD_VENDOR 0

// --- AUDIO CLASS DRIVER CONFIGURATION (UAC1 for Radio) ---
#define CFG_TUD_AUDIO_FUNC_ONLY_AUDIO_DESC 1

#define CFG_TUD_AUDIO_FUNC_1_DESC_FORMAT_TYPE_I_FORMAT_TYPE AUDIO_FORMAT_TYPE_I_PCM
#define CFG_TUD_AUDIO_FUNC_1_DESC_FORMAT_TYPE_I_BIT_RESOLUTION 16
#define CFG_TUD_AUDIO_FUNC_1_DESC_FORMAT_TYPE_I_SUB_SLOT_SIZE 2
#define CFG_TUD_AUDIO_FUNC_1_CHANNEL_COUNT 1

// The audio driver needs to know both directions are in use, and the
// biggest packet size on each, before it will allocate buffers.
#define CFG_TUD_AUDIO_ENABLE_EP_IN 1  // mic path (radio -> PC)
#define CFG_TUD_AUDIO_ENABLE_EP_OUT 1 // speaker path (PC -> radio)

#define CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE 48000

#define CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX 2 // mic (IN)
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX 1
#define CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX 2 // speaker (OUT)
#define CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX 1

#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SZ_MAX TUD_AUDIO_EP_SIZE(TUD_OPT_HIGH_SPEED, CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX)
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SZ_MAX TUD_AUDIO_EP_SIZE(TUD_OPT_HIGH_SPEED, CFG_TUD_AUDIO_FUNC_1_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX)

// Software EP FIFO buffers - must be >= the _SZ_MAX values above
#define CFG_TUD_AUDIO_FUNC_1_EP_OUT_SW_BUF_SZ 256
#define CFG_TUD_AUDIO_FUNC_1_EP_IN_SW_BUF_SZ 256

#endif
